// apps/web-react/src/app/examples/demo-testing/demo-testing.tsx
import './demo-testing.module.scss';
import DemoCounter from './demo-counter/demo-counter';
import { PureComponent } from 'react';

/* eslint-disable-next-line */
export interface DemoTestingProps {}
export interface DemoTestingState {
  counters: number[]
}

export default class DemoTesting extends PureComponent<DemoTestingProps, DemoTestingState> {
  state = {
    counters: [0],
  }

  addCounter = () => {
    this.setState({
      counters: [...this.state.counters, 0]
    });
  }

  render() {
    return (
      <div>
        <h1>Counter</h1>
        <p>See test for more useful information</p>

        <button className="btn btn-secondary add-counter" onClick={this.addCounter}>Add counter</button>

        {this.state.counters.map(counter => {
          return <DemoCounter key="{counter}"></DemoCounter>
        })}

      </div>
    );
  }
}

// apps/web/src/app/examples/demo-testing/demo-testing.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-demo-testing',
  templateUrl: './demo-testing.component.html',
  styleUrls: ['./demo-testing.component.css']
})
export class DemoTestingComponent implements OnInit {

  counters: number[] = [0];

  constructor() { }

  ngOnInit(): void {
  }

  addCounter() {
    this.counters.push(0);
  }

}

<div class="container">
  <h1>Counter</h1>
  <p>See test for more useful information</p>

  <button class="btn btn-secondary" (click)="addCounter()">Add counter</button>

  <div *ngFor="let counter of counters">
    <app-demo-counter class="m-3"></app-demo-counter>
  </div>

</div>
