// apps/web-react/src/app/examples/demo-testing/demo-counter/demo-counter.tsx
import './demo-counter.module.scss';
import { PureComponent } from 'react';
import fetch from 'cross-fetch';

/* eslint-disable-next-line */
export interface DemoCounterProps {}
export interface DemoCounterState {
  counter: number
}

export default class extends PureComponent<DemoCounterProps, DemoCounterState> {
  state = {
    counter: 0,
  }

  componentDidMount() {
    fetch('https://example.com/counter')
      .then(response => response.json())
      .then(data => this.setState({counter: data}))
      .catch(() => null);
  }

  increment = () => {
    this.setState({
      counter: this.state.counter + 1
    });
  }

  decrement = () => {
    this.setState({
      counter: this.state.counter - 1
    });
  }

  randomize = () => {
    this.setState({
      counter: this.state.counter + Math.round(Math.random() * 100)
    });
  }

  render() {
    return (
      <div>
        <h3>
          {this.state.counter}
        </h3>

        <div>
          <button className="btn btn-secondary btn-sm mr-2 increment" onClick={this.increment}>Increment</button>
          <button className="btn btn-secondary btn-sm mr-2 decrement" onClick={this.decrement}>Decrement</button>
          <button className="btn btn-secondary btn-sm mr-2 randomize" onClick={this.randomize}>Randomize</button>
        </div>
      </div>
    );
  }
}

// apps/web/src/app/examples/demo-testing/demo-counter/demo-counter.component.ts
import { Component, OnInit } from '@angular/core';
import {HttpClient} from "@angular/common/http";

@Component({
  selector: 'app-demo-counter',
  templateUrl: './demo-counter.component.html',
  styleUrls: ['./demo-counter.component.css']
})
export class DemoCounterComponent implements OnInit {

  counter = 0;

  constructor(private http: HttpClient) { }

  ngOnInit(): void {
    this.http.get('https://example.com/counter').toPromise().then((counter: number) => {
      this.counter = counter;
    });
  }

  increment() {
    this.counter++;
  }

  decrement() {
    this.counter--;
  }

  randomize() {
    this.counter = Math.round(Math.random() * 100);
  }
}

<div>
  <h3>
    {{counter}}
  </h3>

  <div>
    <button class="btn btn-secondary btn-sm mr-2 increment" (click)="increment()">Increment</button>
    <button class="btn btn-secondary btn-sm mr-2 decrement" (click)="decrement()">Decrement</button>
    <button class="btn btn-secondary btn-sm mr-2 randomize" (click)="randomize()">Randomize</button>
  </div>
</div>
